server:
  port: 8888

spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_HOST:http://localhost:9411/}
    service:
      name: gateway-service
    sender:
      type: web
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        #First service
        - id: first-service
          uri: ${FIRST_SERVICE:http://localhost:8080}
          predicates:
            - Path=/api/v1/first/**
        #Second service
        - id: second-service
          uri: ${SECOND_SERVICE:http://localhost:8081}
          predicates:
            - Path=/api/v1/second/**