server:
  port: 8080
# Spring properties
spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_HOST:http://localhost:9411/}
    service:
      name: first-service
    sender:
      type: web
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  application:
    name: first-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/assets}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      data-locations: classpath:db/initialization/data.sql
      mode: always
      continue-on-error: true


# Actuator properties
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
#Logger
logging:
  level:
    root: info